import { createMutationConstants } from 'destination/store/utilities';

export const NAMESPACE = 'deliveryPlan';

export enum DeliveryPlanActionEnum {
    // Delivery Plan
    RESET_STATE = 'RESET_STATE',
    FETCH_DELIVERY_PLAN = 'FETCH_DELIVERY_PLAN',
    FETCH_ADDITIONAL_REFERENCE = 'FETCH_ADDITIONAL_REFERENCE',
    SAVE_DELIVERY_PLAN = 'SAVE_DELIVERY_PLAN',
    CANCEL_DELIVERY_PLAN = 'CANCEL_DELIVERY_PLAN',
    SET_IS_STOP_OFF_LOCATION = 'SET_IS_STOP_OFF_LOCATION',
    // Delivery Leg
    ADD_DELIVERY_LEG = 'ADD_DELIVERY_LEG',
    COPY_DELIVERY_LEG = 'COPY_DELIVERY_LEG',
    REMOVE_DELIVERY_LEG = 'REMOVE_DELIVERY_LEG',
    CANCEL_DELIVERY_LEG = 'CANCEL_DELIVERY_LEG',
    MOVE_DELIVERY_LEG = 'MOVE_DELIVERY_LEG',
    ACCEPT_DELIVERY_LEG = 'ACCEPT_DELIVERY_LEG',
    REJECT_DELIVERY_LEG = 'REJECT_DELIVERY_LEG',
    UNDO_CANCEL_REJECT_DELIVERY_LEG = 'UNDO_CANCEL_REJECT_DELIVERY_LEG',
    REMOVE_EMPTY_RETURN_LEG = 'REMOVE_EMPTY_RETURN_LEG',
    CHECK_AND_ADD_EMPTY_RETURN_LEG = 'CHECK_AND_ADD_EMPTY_RETURN_LEG',
    CHECK_AND_REMOVE_EMPTY_RETURN_LEG = 'CHECK_AND_REMOVE_EMPTY_RETURN_LEG',
    CHECK_AND_REMOVE_OR_CANCEL_OR_REJECT_EMPTY_RETURN_LEG = 'CHECK_AND_REMOVE_OR_CANCEL_OR_REJECT_EMPTY_RETURN_LEG',
    CHECK_AND_UNSELECT_IS_STOP_OFF_LOCATION = 'CHECK_AND_UNSELECT_IS_STOP_OFF_LOCATION',
}

export const DeliveryPlanMutationEnum = {
    // Delivery Plan
    RESET_STATE: 'RESET_STATE',
    FETCH_DELIVERY_PLAN: createMutationConstants(DeliveryPlanActionEnum.FETCH_DELIVERY_PLAN),
    SAVE_DELIVERY_PLAN: createMutationConstants(DeliveryPlanActionEnum.SAVE_DELIVERY_PLAN),
    CANCEL_DELIVERY_PLAN: 'CANCEL_DELIVERY_PLAN',
    SET_DELIVERY_PLAN_TYPE: 'SET_DELIVERY_PLAN_TYPE',
    SET_IS_STOP_OFF_LOCATION: 'SET_IS_STOP_OFF_LOCATION',
    // Delivery Leg
    SORT_DELIVERY_LEGS: 'SORT_DELIVERY_LEGS',
    RESEQUENCE_DELIVERY_LEGS: 'RESEQUENCE_DELIVERY_LEGS',
    SWAP_DELIVERY_LEGS: 'SWAP_DELIVERY_LEGS',
    ADD_DELIVERY_LEG: 'ADD_DELIVERY_LEG',
    REMOVE_DELIVERY_LEG: 'REMOVE_DELIVERY_LEG',
    CANCEL_DELIVERY_LEG: 'CANCEL_DELIVERY_LEG',
    ACCEPT_DELIVERY_LEG: 'ACCEPT_DELIVERY_LEG',
    REJECT_DELIVERY_LEG: 'REJECT_DELIVERY_LEG',
    CANCEL_OR_REJECT_EMPTY_RETURN_LEG: 'CANCEL_OR_REJECT_EMPTY_RETURN_LEG',
    UNDO_CANCEL_REJECT_DELIVERY_LEG: 'UNDO_CANCEL_REJECT_DELIVERY_LEG',
    // Pick-up
    SET_PICKUP_TIMEZONE_AND_OFFSET: 'SET_PICKUP_TIMEZONE_AND_OFFSET',
    SET_PICKUP_LOCATION: 'SET_PICKUP_LOCATION',
    SET_PICKUP_ON_DATE: 'SET_PICKUP_ON_DATE',
    SET_PICKUP_FROM_TIME: 'SET_PICKUP_FROM_TIME',
    SET_SPECIAL_INSTRUCTION: 'SET_SPECIAL_INSTRUCTION',
    // Delivery
    SET_DELIVERY_TIMEZONE_AND_OFFSET: 'SET_DELIVERY_TIMEZONE_AND_OFFSET',
    SET_DELIVERY_LOCATION: 'SET_DELIVERY_LOCATION',
    SET_DELIVERY_ON_DATE: 'SET_DELIVERY_ON_DATE',
    SET_DELIVERY_TIME_OPTION: 'SET_DELIVERY_TIME_OPTION',
    SET_DELIVERY_FROM_TIME: 'SET_DELIVERY_FROM_TIME',
    SET_DELIVERY_TO_TIME: 'SET_DELIVERY_TO_TIME',
    SET_DELIVERY_REFERENCE: 'SET_DELIVERY_REFERENCE',
    SET_DELIVERY_TYPE: 'SET_DELIVERY_TYPE',
    // Transport
    SET_TRANSPORT_MODE: 'SET_TRANSPORT_MODE',
    SET_TRANSPORT_PROVIDER: 'SET_TRANSPORT_PROVIDER',
    SET_ADDITIONAL_INSTRUCTION: 'SET_ADDITIONAL_INSTRUCTION',
    // Additional Reference(s)
    FETCH_ADDITIONAL_REFERENCE: createMutationConstants(DeliveryPlanActionEnum.FETCH_ADDITIONAL_REFERENCE),
    SET_ADDITIONAL_REFERENCE_FIELD: 'SET_ADDITIONAL_REFERENCE_FIELD',
};

export enum DeliveryPlanGetterEnum {
    GET_DELIVERY_PLAN = 'GET_DELIVERY_PLAN',
    GET_ALL_DELIVERY_LEGS = 'GET_ALL_DELIVERY_LEGS',
    GET_ACTIVE_DELIVERY_LEGS = 'GET_ACTIVE_DELIVERY_LEGS',
    GET_FIRST_ACTIVE_DELIVERY_LEG = 'GET_FIRST_ACTIVE_DELIVERY_LEG',
    GET_LAST_ACTIVE_DELIVERY_LEG = 'GET_LAST_ACTIVE_DELIVERY_LEG',
    GET_ACTIVE_EMPTY_RETURN_LEG = 'GET_ACTIVE_EMPTY_RETURN_LEG',
    GET_CANCELLED_LEGS = 'GET_CANCELLED_LEGS',
    GET_REJECTED_LEGS = 'GET_REJECTED_LEGS',
    GET_ADDITIONAL_REFERENCE = 'GET_ADDITIONAL_REFERENCE',
    GET_IS_STOP_OFF_LOCATION = 'GET_IS_STOP_OFF_LOCATION',
}
