/* istanbul ignore file */

export enum ExportExcelTypeEnum {
    CSA_BULK_UPDATE = 'CSA_BULK_UPDATE',
    CONSIGNEE_BULK_UPDATE = 'CONSIGNEE_BULK_UPDATE',
    CSA_GAS_CHECK = 'CSA_GAS_CHECK',
    CSA_WITH_CURRENT_COLUMNS = 'CSA_WITH_CURRENT_COLUMNS',
    CSA_WITH_ALL_COLUMNS = 'CSA_WITH_ALL_COLUMNS',
    CONSIGNEE_WITH_ALL_COLUMNS = 'CONSIGNEE_WITH_ALL_COLUMNS',
}
