import { createMutationConstants } from 'destination/store/utilities';

export const NAMESPACE = 'filter';

export enum FilterActionEnum {
    SET_BROWSER_QUERY_PARAMS = 'SET_BROWSER_QUERY_PARAMS',
    INITIALIZE_FILTERS = 'INITIALIZE_FILTERS',
    INITIALIZE_APPLIED_FILTERS = 'INITIALIZE_APPLIED_FILTERS',
    SET_APPLIED_FILTERS = 'SET_APPLIED_FILTERS',
    FETCH_CONSIGNEE_OPTIONS = 'FETCH_CONSIGNEE_OPTIONS',
    FETCH_GENERIC_FILTERS_OPTIONS = 'FETCH_GENERIC_FILTERS_OPTIONS',
    FETCH_SAVED_FILTERS = 'FETCH_SAVED_FILTERS',
    SAVE_FILTERS = 'SAVE_FILTERS',
    APPLY_DEFAULT_FILTERS = 'APPLY_DEFAULT_FILTERS',
    DELETE_SAVED_FILTERS = 'DELETE_SAVED_FILTERS',
    UPDATE_DEFAULT_FILTERS = 'UPDATE_DEFAULT_FILTERS',
    FETCH_PLANNING_STATUS = 'FETCH_PLANNING_STATUS',
    FETCH_EXECUTION_STATUS = 'FETCH_EXECUTION_STATUS',
    FETCH_LAST_FREE_DAYS_GROUPS = 'FETCH_LAST_FREE_DAYS_GROUPS',
    FETCH_PRIORITY_LEVEL_GROUPS = 'FETCH_PRIORITY_LEVEL_GROUPS',
    APPLY_SAVED_FILTERS = 'APPLY_SAVED_FILTERS',
    FETCH_LAST_UPDATEDBY_USERS = 'FETCH_LAST_UPDATEDBY_USERS',
}

export const FilterMutationEnum = {
    SET_FILTERS: 'SET_FILTERS',
    SET_APPLIED_FILTERS: FilterActionEnum.SET_APPLIED_FILTERS,
    SET_APPLIED_FILTER_IN_SAVE_FILTERS: 'SET_APPLIED_FILTER_IN_SAVE_FILTERS',
    SET_DEFAULT_FILTER: 'SET_DEFAULT_FILTER',
    SET_IS_INITIALIZED: 'SET_IS_INITIALIZED',
    SET_RESOLVED_APPLIED_FILTERS: 'SET_RESOLVED_APPLIED_FILTERS',
    FETCH_CONSIGNEE_OPTIONS: createMutationConstants(FilterActionEnum.FETCH_CONSIGNEE_OPTIONS),
    FETCH_GENERIC_FILTERS_OPTIONS: createMutationConstants(FilterActionEnum.FETCH_GENERIC_FILTERS_OPTIONS),
    FETCH_SAVED_FILTERS: createMutationConstants(FilterActionEnum.FETCH_SAVED_FILTERS),
    FETCH_PLANNING_STATUS: createMutationConstants(FilterActionEnum.FETCH_PLANNING_STATUS),
    FETCH_EXECUTION_STATUS: createMutationConstants(FilterActionEnum.FETCH_EXECUTION_STATUS),
    FETCH_PRIORITY_LEVEL_GROUPS: createMutationConstants(FilterActionEnum.FETCH_PRIORITY_LEVEL_GROUPS),
    FETCH_LAST_FREE_DAYS_GROUPS: createMutationConstants(FilterActionEnum.FETCH_LAST_FREE_DAYS_GROUPS),
    SAVE_FILTERS: createMutationConstants(FilterActionEnum.SAVE_FILTERS),
    UPDATE_DEFAULT_FILTERS: createMutationConstants(FilterActionEnum.UPDATE_DEFAULT_FILTERS),
    DELETE_SAVED_FILTERS: createMutationConstants(FilterActionEnum.DELETE_SAVED_FILTERS),
    APPLY_DEFAULT_FILTERS: createMutationConstants(FilterActionEnum.APPLY_DEFAULT_FILTERS),
    FETCH_LAST_UPDATEDBY_USERS: createMutationConstants(FilterActionEnum.FETCH_LAST_UPDATEDBY_USERS),
};

export enum FilterGetterEnum {
    GET_SECTIONS = 'GET_SECTIONS',
    GET_QUICK_SECTIONS = 'GET_QUICK_SECTIONS',
    GET_APPLIED_FILTERS = 'GET_APPLIED_FILTERS',
    GET_RESOLVED_APPLIED_FILTERS = 'GET_RESOLVED_APPLIED_FILTERS',
    GET_SAVED_FILTERS = 'GET_SAVED_FILTERS',
    GET_SAVED_FILTER_LOADING_STATUS = 'GET_SAVED_FILTER_LOADING_STATUS',
    GET_PLANNING_STATUS = 'GET_PLANNING_STATUS',
    GET_EXECUTION_STATUS = 'GET_EXECUTION_STATUS',
    GET_LAST_FREE_DAYS_GROUPS = 'GET_LAST_FREE_DAYS_GROUPS',
    GET_PRIORITY_LEVEL_GROUPS = 'GET_PRIORITY_LEVEL_GROUPS',
    GET_SAVED_FILTER_ERROR_MESSAGE = 'GET_SAVED_FILTER_ERROR_MESSAGE',
    GET_APPLIED_FILTER_IN_SAVE_FILTERS = 'GET_APPLIED_FILTER_IN_SAVE_FILTERS',
}
