import { createMutationConstants } from 'destination/store/utilities';

export enum ListActionEnum {
    FETCH_LIST = 'FETCH_LIST',
    ADD_TO_SELECTED_ROWS = 'ADD_TO_SELECTED_ROWS',
    REMOVE_FROM_SELECTED_ROWS = 'REMOVE_FROM_SELECTED_ROWS',
    CLEAR_SELECTED_ROWS = 'CLEAR_SELECTED_ROWS',
    IMPORT_AN_EXCEL = 'IMPORT_AN_EXCEL',
    CLEAR_IMPORT_FILES = 'CLEAR_IMPORT_FILES',
    EXPORT_CSA_BULK_UPDATE = 'EXPORT_CSA_BULK_UPDATE',
    EXPORT_CONSIGNEE_BULK_UPDATE = 'EXPORT_CONSIGNEE_BULK_UPDATE',
    EXPORT_CSA_WITH_CURRENT_COLUMNS = 'EXPORT_CSA_WITH_CURRENT_COLUMNS',
    EXPORT_CSA_WITH_ALL_COLUMNS = 'EXPORT_WITH_ALL_COLUMNS',
    EXPORT_CONSIGNEE_WITH_ALL_COLUMNS = 'EXPORT_CONSIGNEE_WITH_ALL_COLUMNS',
}

export const ListMutationEnum = {
    FETCH_LIST: createMutationConstants(ListActionEnum.FETCH_LIST),
    ADD_TO_SELECTED_ROWS: ListActionEnum.ADD_TO_SELECTED_ROWS,
    REMOVE_FROM_SELECTED_ROWS: ListActionEnum.REMOVE_FROM_SELECTED_ROWS,
    CLEAR_SELECTED_ROWS: ListActionEnum.CLEAR_SELECTED_ROWS,
    IMPORT_AN_EXCEL: createMutationConstants(ListActionEnum.IMPORT_AN_EXCEL),
    CLEAR_IMPORT_FILES: ListActionEnum.CLEAR_IMPORT_FILES,
    EXPORT_EXCEL: createMutationConstants('EXPORT_EXCEL'),
};

export enum ListGetterEnum {
    GET_LIST = 'GET_LIST',
    GET_IMPORT_EXCEL = 'GET_IMPORT_EXCEL',
    GET_SELECTED_ROWS = 'GET_SELECTED_ROWS',
}
