export enum FeatureToggleEnum {
    DP_LCL_LISTVIEW = 'DP_LCL_LISTVIEW',
    DS_EMPTY_RETURN_REFERENCE_FIELDS_TEMP = 'DS_EMPTY_RETURN_REFERENCE_FIELDS_TEMP',
    HIDE_DG_GOH_RFR = 'HideFlagsDG_GOH_RFR',
}
